"""Copy everything from one database to another (for example the local SQLite file into Neon), so the hold-out study,
trained models and news history do not have to be recomputed.
    python scripts/copy_db.py --from store/predictor.db --to "$DATABASE_URL"
Rows that already exist in the target are left alone. Counts are compared at the end."""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from core import store  # noqa: E402

TABLES = ["instruments", "models", "reports", "research", "explanations", "series", "news", "events", "candles",
          "heartbeat", "user_settings", "access_codes", "predictions", "shadow_trades"]
SERIAL = ["predictions", "shadow_trades"]  # tables whose id is generated by the database


def columns(db, table: str) -> list:
    if db.kind == "sqlite":
        return [r[1] for r in db.conn.execute(f"PRAGMA table_info({table})").fetchall()]
    return [r["column_name"] for r in db.execute(
        "SELECT column_name FROM information_schema.columns WHERE table_name = ? ORDER BY ordinal_position", (table,)).fetchall()]


def count(db, table: str) -> int:
    return int(db.execute(f"SELECT COUNT(*) AS n FROM {table}").fetchone()["n"])


def copy(src, dst, log=print) -> dict:
    result = {}
    for t in TABLES:
        cols = [c for c in columns(src, t) if c in set(columns(dst, t))]
        rows = [tuple(r[c] for c in cols) for r in src.execute(f"SELECT {', '.join(cols)} FROM {t}").fetchall()]
        chunk = 1 if t == "models" else max(1, 2000 // len(cols))  # model files are large: one per statement
        for i in range(0, len(rows), chunk):
            part = rows[i:i + chunk]
            dst.execute(f"INSERT INTO {t}({', '.join(cols)}) VALUES "
                        + ",".join(["(" + ",".join("?" * len(cols)) + ")"] * len(part)) + " ON CONFLICT DO NOTHING",
                        [v for r in part for v in r])
        dst.commit()
        if dst.kind == "postgres" and t in SERIAL:  # keep the id counter ahead of the copied ids
            dst.execute(f"SELECT setval(pg_get_serial_sequence('{t}', 'id'), COALESCE((SELECT MAX(id) FROM {t}), 0) + 1, false)")
            dst.commit()
        result[t] = (len(rows), count(dst, t))
        log(f"  {t:14} source {len(rows):6}  target now {result[t][1]:6}")
    return result


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--from", dest="src", required=True)
    ap.add_argument("--to", dest="dst", required=True)
    a = ap.parse_args()
    out = copy(store.connect(a.src), store.connect(a.dst))
    short = {t: v for t, v in out.items() if v[1] < v[0]}
    print("all rows present in the target" if not short else f"MISSING ROWS: {short}")
